{{- if and .Values.tls.autoGenerate (not .Values.tls.certManager.enabled) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "keeper-injector.fullname" . }}-cert-manager
  labels:
    {{- include "keeper-injector.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook-cert-manager
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-2"
    helm.sh/hook-delete-policy: before-hook-creation
{{- end }}
